#!/bin/bash

exec > ~/aws-init.log 2>&1

echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" >> /etc/apt/sources.list.d/docker.list
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
apt-get update
apt-get install -y python python-dev python-pip docker-engine git

\curl -sSL https://get.rvm.io | bash -s stable --ruby
source /usr/local/rvm/scripts/rvm
gem install bundler

pip install buildbot-slave

cd /
git clone --branch newarch https://xassembly-worker:$GIT_TOKEN@github.com/exactassembly/caiman.git

cd /caiman/gatoregg

bundle install
rake

mkdir /build
cd /build

buildslave create-slave slave $MASTER_ADDRESS:9989 build-slave pass
buildslave start slave
