#!/bin/bash

echo 'export GIT_TOKEN=""' >> /etc/aws-init.conf
echo 'export MASTER_ADDRESS=""' >> /etc/aws-init.conf
echo 'export SLAVE_PASS=""' >> /etc/aws-init.conf

echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" >> /etc/apt/sources.list.d/docker.list
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
apt-get update
apt-get install -y python python-dev python-pip docker-engine git

\curl -sSL https://get.rvm.io | bash -s stable --ruby
source /usr/local/rvm/scripts/rvm
gem install bundler

pip install service_identity buildbot-slave awscli

. /etc/aws-init.conf

echo ". /etc/aws-init.conf" >> /home/ubuntu/.bashrc
echo "start on runlevel [2345]" >> /etc/init/buildslave.conf
echo "source /usr/local/rvm/scripts/rvm" >> /etc/init/buildslave.conf
echo "exec buildslave start /build/slave" >> /etc/init/buildslave.conf

cd /
git clone --branch newarch https://xassembly-worker:$GIT_TOKEN@github.com/exactassembly/caiman.git

cd /caiman/gatoregg

bundle install
rake

mkdir /build
cd /build

buildslave create-slave slave $MASTER_ADDRESS:9989 build-slave $SLAVE_PASS

echo "Slave initialization complete."
echo